package quanlitintuc.admin;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import quanlitintuc.utils.DatabaseUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import quanlitintuc.dataContext.CurrentUser;
import quanlitintuc.utils.IMAGE_RESOURCE;

/**
 *
 * @author Anh Bui
 */
public class AddNews extends javax.swing.JFrame {

    private File selectedImageFile; // Biến để lưu trữ tệp tin ảnh đã chọn

    /**
     * Creates new form AddNews
     */
    public AddNews() {
        initComponents();
        // Gọi phương thức để load danh mục vào combo box khi khởi tạo giao diện
        loadDanhMucComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tieuDeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        anhTinTucLabel = new javax.swing.JLabel();
        uploadAnhBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noiDungTxt = new javax.swing.JTextArea();
        dangBaiVietBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        danhMucCboBox = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bản tin mới");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Thêm mới tin tức");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tiêu đề");

        tieuDeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ảnh bài viết");

        anhTinTucLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        uploadAnhBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uploadAnhBtn.setText("Tải ảnh lên");
        uploadAnhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadAnhBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nội dung");

        noiDungTxt.setColumns(20);
        noiDungTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noiDungTxt.setRows(5);
        jScrollPane1.setViewportView(noiDungTxt);

        dangBaiVietBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dangBaiVietBtn.setForeground(new java.awt.Color(51, 153, 0));
        dangBaiVietBtn.setText("Đăng bài");
        dangBaiVietBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangBaiVietBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh mục");

        danhMucCboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        danhMucCboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhMucCboBoxActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tieuDeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anhTinTucLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(danhMucCboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadAnhBtn))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dangBaiVietBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tieuDeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(anhTinTucLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(danhMucCboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(uploadAnhBtn)
                                .addGap(0, 84, Short.MAX_VALUE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(dangBaiVietBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadAnhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadAnhBtnActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = fileChooser.getSelectedFile();
            String imagePath = selectedImageFile.getAbsolutePath();

            // Tạo một ImageIcon từ đường dẫn ảnh
            ImageIcon imageIcon = new ImageIcon(imagePath);

            // Lấy kích thước hiện thời của label
            int labelWidth = anhTinTucLabel.getWidth();
            int labelHeight = anhTinTucLabel.getHeight();

            // Resize ảnh theo kích thước của label
            Image image = imageIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

            // Tạo một ImageIcon mới từ ảnh đã được resize
            ImageIcon resizedImageIcon = new ImageIcon(image);

            // Hiển thị ảnh trên label
            anhTinTucLabel.setIcon(resizedImageIcon);

        }
    }//GEN-LAST:event_uploadAnhBtnActionPerformed

    private void dangBaiVietBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangBaiVietBtnActionPerformed
        String tieuDe = tieuDeTxt.getText();
        String noiDung = noiDungTxt.getText();
        String danhMuc = danhMucCboBox.getSelectedItem().toString();

        // Kiểm tra xem đã chọn ảnh hay chưa
        if (selectedImageFile == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ảnh");
            return;
        }

        try {
            Connection connection = DatabaseUtils.getConnection();

            // Lấy id của danh mục từ tên danh mục
            String getCategoryIdQuery = "SELECT id FROM categories WHERE name = ?";
            PreparedStatement getCategoryIdStmt = connection.prepareStatement(getCategoryIdQuery);
            getCategoryIdStmt.setString(1, danhMuc);
            ResultSet resultSet = getCategoryIdStmt.executeQuery();
            if (!resultSet.next()) {
                JOptionPane.showMessageDialog(this, "Danh mục không tồn tại");
                return;
            }
            int categoryId = resultSet.getInt("id");
            int authorId = getAuthorId(CurrentUser.username);

            // Tạo tên cơ sở (basename) cho ảnh
            String imageBasename = selectedImageFile.getName();

            // Tạo đường dẫn mới cho ảnh trong thư mục lưu trữ
            String newImagePath = IMAGE_RESOURCE.SOURCE_PATH + imageBasename;

            // Di chuyển file ảnh gốc vào thư mục lưu trữ
            File newImageFile = new File(newImagePath);
            Files.copy(selectedImageFile.toPath(), newImageFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

            // Thực hiện câu lệnh insert bài viết mới vào cơ sở dữ liệu
            String insertNewsQuery = "INSERT INTO news (title, image, content, created_date, author_id, category_id) VALUES (?, ?, ?, current_timestamp(), ?, ?)";
            PreparedStatement insertNewsStmt = connection.prepareStatement(insertNewsQuery, PreparedStatement.RETURN_GENERATED_KEYS);

            insertNewsStmt.setString(1, tieuDe);
            insertNewsStmt.setString(2, imageBasename);
            insertNewsStmt.setString(3, noiDung);
            insertNewsStmt.setInt(4, authorId);
            insertNewsStmt.setInt(5, categoryId);
            insertNewsStmt.executeUpdate();

            // Lấy id của bài viết mới được tạo
            ResultSet generatedKeys = insertNewsStmt.getGeneratedKeys();
            int newNewsId;
            if (generatedKeys.next()) {
                newNewsId = generatedKeys.getInt(1);

                // Hiển thị thông báo thành công
                JOptionPane.showMessageDialog(this, "Đăng bài viết thành công!");

                // Reset các trường dữ liệu
                tieuDeTxt.setText("");
                noiDungTxt.setText("");
                anhTinTucLabel.setIcon(null);
            } else {
                JOptionPane.showMessageDialog(this, "Đăng bài viết không thành công");
            }

            // Đóng kết nối và tài nguyên
            insertNewsStmt.close();
            getCategoryIdStmt.close();
            connection.close();

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_dangBaiVietBtnActionPerformed

    private void danhMucCboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhMucCboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_danhMucCboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        NewsManagement management = new NewsManagement();
        management.setVisible(true);
        this.dispose(); // Đóng cửa sổ 
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new AddNews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhTinTucLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton dangBaiVietBtn;
    private javax.swing.JComboBox<String> danhMucCboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noiDungTxt;
    private javax.swing.JTextField tieuDeTxt;
    private javax.swing.JButton uploadAnhBtn;
    // End of variables declaration//GEN-END:variables

    private void loadDanhMucComboBox() {
        try {
            // Kết nối cơ sở dữ liệu
            Connection connection = DatabaseUtils.getConnection();

            // Truy vấn danh sách danh mục từ bảng "categories"
            String query = "SELECT name FROM categories";
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            // Tạo một model cho combo box
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

            // Thêm từng danh mục vào model
            while (resultSet.next()) {
                String categoryName = resultSet.getString("name");
                comboBoxModel.addElement(categoryName);
            }

            // Thiết lập model cho combo box
            danhMucCboBox.setModel(comboBoxModel);

            // Đóng kết nối và giải phóng tài nguyên
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            // Xử lý lỗi kết nối hoặc truy vấn cơ sở dữ liệu
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh mục từ cơ sở dữ liệu",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private int getAuthorId(String username) {
        try {
            Connection connection = DatabaseUtils.getConnection();
            String query = "SELECT id FROM users WHERE username = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, username);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                return resultSet.getInt("id");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1; // Trả về -1 nếu không tìm thấy author_id
    }

}
