package quanlitintuc.admin;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import quanlitintuc.utils.DatabaseUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import quanlitintuc.dataContext.CurrentUser;
import quanlitintuc.utils.IMAGE_RESOURCE;

/**
 *
 * @author Anh Bui
 */
public class AddOrUpdateNews extends javax.swing.JFrame {

    private File selectedImageFile; // Biến để lưu trữ tệp tin ảnh đã chọn
    private int newsId;

    /**
     * Creates new form AddNews
     */
    public AddOrUpdateNews() {
        initComponents();
        // Gọi phương thức để load danh mục vào combo box khi khởi tạo giao diện
        loadDanhMucComboBox();
        setLocationRelativeTo(null);
    }

    public AddOrUpdateNews(int newsId) {
        initComponents();
        this.newsId = newsId;
        loadDanhMucComboBox();
        displayNewsInfo();
        setLocationRelativeTo(null);
    }

    private void displayNewsInfo() {
    try {
        Connection connection = DatabaseUtils.getConnection();

        // Query to get news information by newsId
        String getNewsInfoQuery = "SELECT * FROM news WHERE id = ?";
        PreparedStatement getNewsInfoStmt = connection.prepareStatement(getNewsInfoQuery);
        getNewsInfoStmt.setInt(1, newsId);
        ResultSet resultSet = getNewsInfoStmt.executeQuery();

        if (resultSet.next()) {
            String title = resultSet.getString("title");
            String image = resultSet.getString("image");
            String content = resultSet.getString("content");
            int categoryId = resultSet.getInt("category_id");

            tieuDeTxt.setText(title);
            noiDungTxt.setText(content);
            danhMucCboBox.setSelectedItem(getCategoryName(categoryId));

            String imagePath = IMAGE_RESOURCE.SOURCE_PATH + image;
            File imageFile = new File(imagePath);
            if (imageFile.exists()) {
                // Gán giá trị cũ cho selectedImageFile
                selectedImageFile = imageFile;

                ImageIcon imageIcon = new ImageIcon(imagePath);
                
                anhTinTucLabel.setIcon(imageIcon);
            }
        }

        getNewsInfoStmt.close();
        connection.close();

    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tieuDeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        anhTinTucLabel = new javax.swing.JLabel();
        uploadAnhBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noiDungTxt = new javax.swing.JTextArea();
        taoCapNhatBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        danhMucCboBox = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bản tin mới");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Thêm mới tin tức");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tiêu đề");

        tieuDeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ảnh bài viết");

        uploadAnhBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uploadAnhBtn.setText("Tải ảnh lên");
        uploadAnhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadAnhBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nội dung");

        noiDungTxt.setColumns(20);
        noiDungTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noiDungTxt.setLineWrap(true);
        noiDungTxt.setRows(5);
        noiDungTxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(noiDungTxt);

        taoCapNhatBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        taoCapNhatBtn.setForeground(new java.awt.Color(51, 153, 0));
        taoCapNhatBtn.setText("Tạo/Cập nhật");
        taoCapNhatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taoCapNhatBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh mục");

        danhMucCboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        danhMucCboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhMucCboBoxActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tieuDeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anhTinTucLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(danhMucCboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadAnhBtn))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taoCapNhatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tieuDeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(anhTinTucLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(danhMucCboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(uploadAnhBtn)
                                .addGap(0, 84, Short.MAX_VALUE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(taoCapNhatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadAnhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadAnhBtnActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = fileChooser.getSelectedFile();
            String imagePath = selectedImageFile.getAbsolutePath();

            // Tạo một ImageIcon từ đường dẫn ảnh
            ImageIcon imageIcon = new ImageIcon(imagePath);

            // Lấy kích thước hiện thời của label
            int labelWidth = anhTinTucLabel.getWidth();
            int labelHeight = anhTinTucLabel.getHeight();

            // Resize ảnh theo kích thước của label
            Image image = imageIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

            // Tạo một ImageIcon mới từ ảnh đã được resize
            ImageIcon resizedImageIcon = new ImageIcon(image);

            // Hiển thị ảnh trên label
            anhTinTucLabel.setIcon(resizedImageIcon);

        }
    }//GEN-LAST:event_uploadAnhBtnActionPerformed

    private void taoCapNhatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taoCapNhatBtnActionPerformed
        saveNews();
    }//GEN-LAST:event_taoCapNhatBtnActionPerformed

    private void danhMucCboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhMucCboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_danhMucCboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        NewsManagement management = new NewsManagement();
        management.setVisible(true);
        this.dispose(); // Đóng cửa sổ 
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new AddOrUpdateNews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhTinTucLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> danhMucCboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noiDungTxt;
    private javax.swing.JButton taoCapNhatBtn;
    private javax.swing.JTextField tieuDeTxt;
    private javax.swing.JButton uploadAnhBtn;
    // End of variables declaration//GEN-END:variables

    private void loadDanhMucComboBox() {
        try {
            // Kết nối cơ sở dữ liệu
            Connection connection = DatabaseUtils.getConnection();

            // Truy vấn danh sách danh mục từ bảng "categories"
            String query = "SELECT name FROM categories";
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            // Tạo một model cho combo box
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

            // Thêm từng danh mục vào model
            while (resultSet.next()) {
                String categoryName = resultSet.getString("name");
                comboBoxModel.addElement(categoryName);
            }

            // Thiết lập model cho combo box
            danhMucCboBox.setModel(comboBoxModel);

            // Đóng kết nối và giải phóng tài nguyên
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            // Xử lý lỗi kết nối hoặc truy vấn cơ sở dữ liệu
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh mục từ cơ sở dữ liệu",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private int getAuthorId(String username) {
        try {
            Connection connection = DatabaseUtils.getConnection();
            String query = "SELECT id FROM users WHERE username = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, username);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                return resultSet.getInt("id");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1; // Trả về -1 nếu không tìm thấy author_id
    }

    private void saveNews() {
        String title = tieuDeTxt.getText();
        String content = noiDungTxt.getText();
        String category = danhMucCboBox.getSelectedItem().toString();

        if (content.isEmpty() || category.isEmpty() || selectedImageFile == null) {
//            System.out.println(content);
//            System.out.println(category);
//            System.out.println(selectedImageFile);

            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection connection = DatabaseUtils.getConnection();

            String getCategoryIdQuery = "SELECT id FROM categories WHERE name = ?";
            PreparedStatement getCategoryIdStmt = connection.prepareStatement(getCategoryIdQuery);
            getCategoryIdStmt.setString(1, category);
            ResultSet resultSet = getCategoryIdStmt.executeQuery();

            if (resultSet.next()) {
                int categoryId = resultSet.getInt("id");

                if (newsId == 0) {
                    // Insert bài viết mới
                    String insertNewsQuery = "INSERT INTO news (title, image, content, category_id, author_id) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement insertNewsStmt = connection.prepareStatement(insertNewsQuery);
                    insertNewsStmt.setString(1, title);
                    insertNewsStmt.setString(2, selectedImageFile.getName());
                    insertNewsStmt.setString(3, content);
                    insertNewsStmt.setInt(4, categoryId);
                    insertNewsStmt.setInt(5, getAuthorId(CurrentUser.username));
                    insertNewsStmt.executeUpdate();
                    insertNewsStmt.close();
                } else {
                    // Update bài viết
                    String updateNewsQuery = "UPDATE news SET title = ?, image = ?, content = ?, category_id = ? WHERE id = ?";
                    PreparedStatement updateNewsStmt = connection.prepareStatement(updateNewsQuery);
                    updateNewsStmt.setString(1, title);
                    updateNewsStmt.setString(2, selectedImageFile.getName());
                    updateNewsStmt.setString(3, content);
                    updateNewsStmt.setInt(4, categoryId);
                    updateNewsStmt.setInt(5, newsId);
                    updateNewsStmt.executeUpdate();
                    updateNewsStmt.close();
                }

                File destination = new File(IMAGE_RESOURCE.SOURCE_PATH + selectedImageFile.getName());
                Files.copy(selectedImageFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);

                JOptionPane.showMessageDialog(this, "Tạo/cập nhật bài viết thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                NewsManagement management = new NewsManagement();
                management.setVisible(true);
                this.dispose(); // Đóng cửa sổ 

            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy danh mục", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

            getCategoryIdStmt.close();
            connection.close();

        } catch (SQLException | IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu bài viết", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static String getCategoryName(int categoryId) {
        String categoryName = null;

        try (Connection connection = DatabaseUtils.getConnection()) {
            String query = "SELECT name FROM categories WHERE id = ?";
            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setInt(1, categoryId);
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        categoryName = resultSet.getString("name");
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return categoryName;
    }
}
