package quanlitintuc.user;

import java.io.File;
import javax.swing.ImageIcon;
import quanlitintuc.utils.DatabaseUtils;
import java.sql.*;
import quanlitintuc.utils.IMAGE_RESOURCE;

public class NewsDetails extends javax.swing.JFrame {

    private int newsId; // Thêm thuộc tính newsId

    /**
     * Creates new form NewsDetails
     */
    public NewsDetails(int newsId) {
        initComponents();
        this.newsId = newsId; // Gán giá trị newsId từ tham số vào thuộc tính
        setLocationRelativeTo(null);
        heading.setText("Chi tiết tin tức ID: " + this.newsId);
        loadNewsData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        anhBaiVietLabel = new javax.swing.JLabel();
        tieuDeTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noiDungTxt = new javax.swing.JTextArea();
        xemBinhLuanBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        tacGiaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiết tin tức");

        heading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(204, 51, 0));
        heading.setText("Chi tiết tin tức");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tiêu đề");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ảnh bài viết");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nội dung");

        tieuDeTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        noiDungTxt.setEditable(false);
        noiDungTxt.setColumns(20);
        noiDungTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noiDungTxt.setLineWrap(true);
        noiDungTxt.setRows(5);
        noiDungTxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(noiDungTxt);

        xemBinhLuanBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        xemBinhLuanBtn.setForeground(new java.awt.Color(102, 102, 0));
        xemBinhLuanBtn.setText("Xem bình luận");
        xemBinhLuanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemBinhLuanBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        tacGiaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tacGiaLabel.setText("Tác giả :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(tieuDeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anhBaiVietLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tacGiaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(xemBinhLuanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heading)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tacGiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tieuDeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(anhBaiVietLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(xemBinhLuanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        NewsList list = new NewsList();
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void xemBinhLuanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemBinhLuanBtnActionPerformed
        CommentsList commentsList = new CommentsList(newsId);
        commentsList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_xemBinhLuanBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhBaiVietLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noiDungTxt;
    private javax.swing.JLabel tacGiaLabel;
    private javax.swing.JLabel tieuDeTxt;
    private javax.swing.JButton xemBinhLuanBtn;
    // End of variables declaration//GEN-END:variables

    private String getAuthorFullName(int newsId) {
        String authorFullName = "";
        try {
            Connection connection = DatabaseUtils.getConnection();

            // Truy vấn để lấy ra full_name của user thông qua news_id
            String sql = "SELECT users.full_name FROM users INNER JOIN news ON users.id = news.author_id WHERE news.id = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setInt(1, newsId);
            ResultSet resultSet = statement.executeQuery();

            // Kiểm tra xem có kết quả trả về hay không
            if (resultSet.next()) {
                authorFullName = resultSet.getString("full_name");
            }

            // Đóng kết nối và giải phóng tài nguyên
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Xử lý lỗi
        }

        return authorFullName;

    }

    private void loadNewsData() {
        try {
            Connection connection = DatabaseUtils.getConnection();

            // Lấy dữ liệu của tin tức từ cơ sở dữ liệu
            String sql = "SELECT title, image, content FROM news WHERE id = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setInt(1, newsId);
            ResultSet resultSet = statement.executeQuery();
            String authorFullName = getAuthorFullName(newsId);
            tacGiaLabel.setText("Tác giả: " + authorFullName);
            // Kiểm tra xem có kết quả trả về hay không
            if (resultSet.next()) {
                String title = resultSet.getString("title");
                String image = resultSet.getString("image");
                String content = resultSet.getString("content");

                // Hiển thị dữ liệu lên giao diện
                tieuDeTxt.setText(title);
                // Lấy đường dẫn tới tệp ảnh
                String imagePath = IMAGE_RESOURCE.SOURCE_PATH + image;

                File imageFile = new File(imagePath);
                if (imageFile.exists()) {
                    ImageIcon icon = new ImageIcon(imagePath);
                    anhBaiVietLabel.setIcon(icon); // Đảm bảo ảnh phù hợp với JLabel

                } else {
                    System.err.println("Không tìm thấy ảnh: " + imagePath);
                }
                noiDungTxt.setText(content);
            }

            // Đóng kết nối và giải phóng tài nguyên
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Xử lý lỗi
        }
    }

}
